---
title: "Envejecimiento poblacional y su efecto en la desigualdad social - laboral"
format: html
editor: visual
bibliography: Vejez poblacional.bib
link-citations: true
---

## Trabajo 1 R

#### **Por Josefa Gatica V.**

El envejecimiento poblacional es un fenómeno mundial, esto trae consigo, distintas consecuencias. En el caso de América Latina, especialmente en Chile, tiene incentivos con el efecto contrario, como el bono por hijo; a través de ChileAtiende. En Italia, ofrece a la población joven habitar zonas despobladas con facilidades de acceso a trabajo, casa y un grado de bonificación monetaria.

Está bien, pero si lo vemos desde un plano más significativo como en Latinoamérica, que es una región potencialmente económica de índole alimenticia y de extracción de recursos naturales [@angulo-bustinzaTradeInclusiveEconomic2023], pero, con carencias como del resguardo social y medioambiental [@schulteIdentifyingCriticalVegetation2024]. Se verá las medidas tomadas por países de Chile específicamente y países vecinos como Colombia , Ecuador y México.

Hay aumento de la desigualdad económica y carencia en el resguardo social de la tercera edad. La Administradora de Fondos de Pensiones "AFP"; sistema usado en Chile, no es el mejor apaciguador de las necesidades. Es una gran problemática que el dinero perteneciente del esfuerzo, siendo insuficiente, genera la necesidad de seguir trabajando, estando jubilado y no recibir una calidad de vida ni asistencia de salud digna.

Dentro del aporte científico, es una contingencia que puede que no sea tomado con la consideración suficiente, pero, próximamente se necesitará de mejoras sociales. Por lo cual, involucrará de un trabajo político económico y social. Así también hay que ser realistas, ellos son más vulnerables por la edad, en unos años más, habrá un aumento significativo de la cantidad de adultos mayores. Por tanto, puede llegar a un descontrol de la dosificación de insumos o de soluciones para tantas personas con necesidades.

Con estos antecedentes se estudiará cómo el envejecimiento poblacional traerá mayores consecuencias sociales, económicas y políticas para el país chileno. Sociales, en el sentido de una mejor calidad de vida para los ciudadanos, por consiguiente, resguardo social de ellos. Económico, si bien encontrándonos con una inflación actualmente (2024), dificulta el acceso a servicios básicos y esto trae consigo mayor esfuerzo de un adulto mayor, a un trabajo que suele ser forzoso y tener repercusiones en su salud, además de ser propensos a requerir de asistencia médica. El estado tendrá que ver como apoyar económicamente a la población con menor interés, al no ser una población activa económicamente. Político, ya que, se requiere de ciertas políticas públicas que los resguarde y dé una mejor solución a esta problemática. Con esto podremos promover una posible prevención o implementación de soluciones para el desafío que se avecina, como también, no olvidar que este grupo es muy propenso a la pobreza o una pobreza multidimensional, por tanto, estarán en una vulnerabilidad mayor a la que se encuentran.

La calidad de vida también trae consecuencias como la autoestima. Siendo una investigación realizada en Ecuador, se comprueba que el acceso a salud es percibido como un indicador de calidad de vida en el adulto mayor, unido a los otros factores. Por consiguiente, en el autoestima; y a nivel político social, una disminución en los recursos públicos que contribuyan a un envejecimiento de calidad [@CALIDADVIDAAUTOESTIMA2022]. En Chile, la figura de la persona mayor en la historia ha ido perdiendo su importancia hasta quedar reducido, neutralizado e invalidado. Al no ser suficiente también la institucionalidad, los distintos poderes del Estado y la legislación así nos lo demuestran, dando poco valor al trato que debe dársele y hoy la vejez convierte al ser humano en ciudadano de segunda o tercera clase, consiguiendo privarlo de su dignidad y, por tanto, de todo lo que ello conlleva en su calidad de ser humano [@martinezmardonesProteccionPersonasMayores2023]. Habiendo una injusticia y desvalorización tan grande, en México, El panorama institucional parece estar en contra de que tengan derecho de una jubilación digna. Se identifican las debilidades del sistema de pensiones mexicanos aplicado al caso de los trabajadores campesinos mexicanos. No muy distinto en el caso de Chile, aun así, en México tuvo de resultado una las acuciantes condiciones del mercado de trabajo de los jornaleros agrícolas y su bajo acceso a los sistemas de pensiones diseñados por el Estado son culpa del propio Estado que los deja en un estado de indefensión y pobreza al no permitirles el acceso a una pensión digna por los requisitos para acceder a ella [@hernandeztrujilloElderlyWorkSocial2023].

El desarrollo de políticas públicas para personas mayores ha implicado un cambio significativo en la perspectiva, integrando factores políticos, ideológicos y económicos disruptivos. Donde el cuidado de las personas mayores requiere de importancia. Las estrategias para el envejecimiento futuro reconocen que las capacidades de los ancianos no solo dependen de su salud física o mental, sino también del entorno, los recursos disponibles y su interacción social.[@ariasEnvejecimientoPoblacionalenAmerica2020].

La región desgraciadamente no tiene consecuencias distintas a este acontecimiento, es una realidad regional compartida, por tanto, se requiere de mejoras y preparación con las mejores herramientas posibles para abarcarlo. En este sentido, considerando el contexto del envejecimiento poblacional como un fenómeno global, se plantea la hipótesis de que en el caso específico de Chile y otros países latinoamericanos, este proceso generará consecuencias sociales, económicas y políticas significativas. Se espera que el aumento demográfico de la tercera edad generará mayor presión en los sistemas de seguridad social existentes, como el sistema de pensiones chileno, exacerbando la desigualdad económica y la vulnerabilidad social. Asimismo, se anticipa que la falta de políticas públicas adecuadas para el cuidado y la inclusión de las personas mayores podría llevar a un deterioro en su calidad de vida, afectando su autoestima y perpetuando su marginalización en la sociedad. Esta situación demandará intervenciones políticas, económicas y sociales profundas para garantizar el bienestar y la dignidad de la población adulta mayor en la región. En este sentido, se necesitará un involucramiento y compromiso por parte del estado. Conforme a ello, tiene la obligación de resguardar los derechos de las personas sin discriminación etaria. Estas mejoras y preparación requerirán de un enfoque integral, con políticas que aborden tanto las necesidades económicas como sociales de este segmento de la población, asegurando así su inclusión plena en la sociedad y su acceso a una vida digna en su etapa de vejez.
